[listener]
type="agent"
listen=":1337"

[[port]]
port="tcp/8022"
services=["ssh-simulator"]

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[channel.console]
type="console"

[channel.elasticsearch]
type="elasticsearch"
url="http://elasticsearch:9200/honeytrap-agent"

[[filter]]
channel=["console", "elasticsearch"]

[[logging]]
output="stdout"
level="debug"
