[listener]
type="socket"

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
ports=["tcp/8022"]
services=["ssh-simulator"]

[channel.console]
type="console"

[channel.elasticsearch]
type="elasticsearch"
url="http://127.0.0.1:9200/honeytrap"

[[filter]]
channel=["console","elasticsearch"]

[[logging]]
output = "stdout"
level = "debug"
